### ISSUE TITLE
Image storage

### ISSUE THREAD

**Issue by ohld** [ecochia/ecochia-wiki#1]

**Comment by serafimcloud** [comment]
![Frame 4](https://user-images.githubusercontent.com/55061526/124346028-28985e00-dbe5-11eb-9c15-643399dfb291.png)
![Frame 5](https://user-images.githubusercontent.com/55061526/124346030-29c98b00-dbe5-11eb-9b46-3f0cca1ed178.png)
![Frame 6](https://user-images.githubusercontent.com/55061526/124346031-2afab800-dbe5-11eb-9cf3-ac0f93d1420f.png)
)
![Frame 2](https://user-images.githubusercontent.com/55061526/124346023-246c4080-dbe5-11eb-8738-49274feb596b.png)
![Frame 3](https://user-images.githubusercontent.com/55061526/124346027-26360400-dbe5-11eb-834b-69b2ad93ae69.png)

**Comment by serafimcloud** [comment]
![Frame 1](https://user-images.githubusercontent.com/55061526/124346088-85941400-dbe5-11eb-947e-bcec4b6e32c2.png)

**Comment by serafimcloud** [comment]
![Frame 8](https://user-images.githubusercontent.com/55061526/124356895-59968400-dc21-11eb-99b6-9fe2b2f9baef.png)

**Comment by serafimcloud** [comment]
![Frame 9](https://user-images.githubusercontent.com/55061526/124357043-1be62b00-dc22-11eb-87eb-7b698edb798d.png)

**Comment by scloud375** [comment]
![Open Graph Banner](https://user-images.githubusercontent.com/55061526/127100098-0c3146e1-bd01-43fb-97f7-d6efd385ae00.png)

**Comment by scloud375** [comment]
![Open Graph Banner](https://user-images.githubusercontent.com/55061526/127100821-17ace2bc-0057-4342-9558-868fe448da4d.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127116129-2fca12ca-7aa3-4ad5-ba6c-fdfd80ae27df.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127116639-a95a5812-3aa8-47c2-bf46-fc6aef9d596d.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127116748-1277ef66-8882-458b-8c35-25f8c36b7940.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127117120-713052a4-2a75-41cb-b3e6-8b89f162ba73.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127120111-5fe9895b-4a45-438b-8a83-264efb053771.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127120269-1b8f835e-c5e7-43a6-abc8-09a09f8545e1.png)

**Comment by scloud375** [comment]
![Frame 2446](https://user-images.githubusercontent.com/55061526/127120474-3ab45c63-1619-4067-8dee-b0647d3bbfe4.png)
